stages: [build, push]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: "1"
  DOCKER_HOST: tcp://docker:2375

  ECR_URL: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  IMAGE: "$ECR_URL/$ECR_REPO"

build:
  stage: build
  image: docker:26
  services:
    - name: docker:26-dind
      alias: docker
      command: ["--mtu=1450"]
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_URL"
  script:
    - docker build -t "$IMAGE:$CI_COMMIT_SHORT_SHA" -t "$IMAGE:latest" -f Dockerfile .
  only:
    - main
    - master
  artifacts:
    expire_in: 1h
    paths: []

push:
  stage: push
  image: docker:26
  services:
    - name: docker:26-dind
      alias: docker
      command: ["--mtu=1450"]
  needs: [build]
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_URL"
  script:
    - docker push "$IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$IMAGE:latest"
  only:
    - main
    - master
