stages: [build_and_push]

variables:
  # AWS/ECR
  ECR_URL: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  IMAGE: "$ECR_URL/$ECR_REPO"

build_and_push:
  stage: build_and_push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - apk add --no-cache aws-cli
    - mkdir -p /kaniko/.docker
    - export ECR_TOKEN="$(aws ecr get-login-password --region "$AWS_DEFAULT_REGION")"
    - echo "{\"auths\":{\"$ECR_URL\":{\"username\":\"AWS\",\"password\":\"$ECR_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --destination "${IMAGE}:${CI_COMMIT_SHORT_SHA}" \
      --cache=true \
      --single-snapshot
    - /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --destination "${IMAGE}:latest" \
      --cache=true \
      --single-snapshot
  only:
    - main
    - master
