version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://docker:docker@postgres:5432/pao-dos-pobres-database?schema=public"
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pao-dos-pobres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
